[ERROR] 2019-02-28 15:37:42.895 [main] Database - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'brewmeister'@'localhost' to database 'brewmeister_test'
[ERROR] 2019-02-28 15:42:02.820 [main] Database - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'brewmeister'@'localhost' to database 'brewmeister_test'
[ERROR] 2019-02-28 15:42:46.370 [main] Database - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'brewmeister'@'localhost' to database 'brewmeister_test'
[ERROR] 2019-02-28 15:44:41.144 [main] Database - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'brewmeister'@'localhost' to database 'brewmeister_test'
[ERROR] 2019-02-28 17:30:18.231 [main] Database - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'brewmeister'@'localhost' to database 'brewmeister_test'
[ERROR] 2019-02-28 17:31:24.201 [main] Database - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'brewmeister'@'localhost' to database 'brewmeister_test'
[INFO ] 2019-02-28 17:31:27.479 [main] UserDAOTest - running getByID test
[ERROR] 2019-02-28 17:39:55.426 [main] Database - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'brewmeister'@'localhost' to database 'brewmeister_test'
[ERROR] 2019-02-28 17:58:14.279 [main] Database - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'brewmeister'@'localhost' to database 'brewmeister_test'
[ERROR] 2019-02-28 17:59:10.360 [main] Database - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'brewmeister'@'localhost' to database 'brewmeister_test'
[ERROR] 2019-02-28 18:04:43.493 [main] Database - java.sql.SQLException: Access denied for user 'brewmeister_test'@'localhost' (using password: YES)
[ERROR] 2019-02-28 18:06:18.415 [main] Database - java.sql.SQLException: Access denied for user 'brewmeister_test2'@'localhost' (using password: YES)
[ERROR] 2019-02-28 18:07:12.322 [main] Database - java.sql.SQLException: Access denied for user 'brewmeister_test'@'localhost' (using password: YES)
[ERROR] 2019-02-28 18:08:03.386 [main] Database - java.sql.SQLException: Access denied for user 'brewmeister_test'@'localhost' (using password: YES)
[ERROR] 2019-02-28 18:15:43.920 [main] Database - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'brewmeister_test.users' doesn't exist
